### ISSUE TITLE
Using wrong MQTT topic for printing

### ISSUE THREAD

**Issue by RoadkillUK** [BeardedTinker/ESP8266-MQTT-Thermal-Printer-for-HA#6]
Line 119 reads ...
 if (strcmp(topic,mqtt_listen_topic_textsize)==0){

It should read ...
 if (strcmp(topic,mqtt_listen_topic_barcode)==0){

**Comment by lebherz** [comment]
Hi @RoadkillUK  why?
did you see line 92 for barcode?
line 119 prints "Message arrived".
Line 119 is for Text-messages. Line 92 for Barcode. :)

**Comment by RoadkillUK** [comment]
Sorry, I got that bit wrong (I blame cut&paste) ;)

It should read ...
 if (strcmp(topic,mqtt_listen_topic_text2print)==0){

There is no mention of text2print in the .ino otherwise .. took me ages to work out why it wasn't printing.

**Comment by BeardedTinker** [comment]
Thanks @RoadkillUK  and @lebherz !!
